server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files \$uri /index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Redireciona chamadas de API para o Load Balancer do Backend
    location /api/ {
        proxy_pass http://${lb_dns_name}:8080/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }

    location /lambda/ {
        # O Nginx vai remover o "/lambda/" e passar o resto para o Gateway
        # Ex: chamando /lambda/solicitar-relatorio vai para o Gateway/solicitar-relatorio
        proxy_pass ${api_gateway_url}/; 
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        
        # Importante para APIs da AWS (API Gateway exige o SNI correto)
        proxy_ssl_server_name on;
    }
}